from pathlib import Path
import plotly.express as px
import streamlit as st
from components.figures import endotype_heatmap
from components.layout import intro, source_box
from data.loaders import load_tsv, optional_tsv
from data.transforms import endotype_means
from data.validators import msg_modules, one_to_one


def render(root: Path) -> None:
    st.header("MSG Endotype Explorer")
    intro("How do MSG-derived molecular modules organize heterogeneity within SjD?",
          "This view summarizes the preliminary assignments already generated by the R pipeline.")
    base = root / "02_wgcna_endotypes_projection"
    assignments = load_tsv(base / "04_preliminary_endotypes_SjD.tsv", ("patient_id", "endotype", "disease_group"), ("patient_id",))
    eig = load_tsv(base / "02_MSG_module_eigengenes_z.tsv", ("patient_id",), ("patient_id",))
    assigned = assignments.dropna(subset=["endotype"])
    st.metric("SjD patients with assigned endotype", int(len(assigned)))
    sizes = assigned.groupby("endotype").size().rename("patients").reset_index()
    st.plotly_chart(px.bar(sizes, x="endotype", y="patients", color="endotype", text_auto=True,
                           title="Assigned SjD patients by endotype"), use_container_width=True)
    st.plotly_chart(endotype_heatmap(endotype_means(assignments, eig)), use_container_width=True)
    joined = one_to_one(assigned[["patient_id", "endotype"]], eig, "Endotype distribution")
    mapping = msg_modules(eig); module = st.selectbox("MSG module", list(mapping))
    st.plotly_chart(px.box(joined, x="endotype", y=mapping[module], color="endotype", points=False,
                           labels={mapping[module]: "MSG eigengene z-score", "endotype": "Endotype"}), use_container_width=True)
    sil = optional_tsv(base / "04_silhouette_SjD.tsv", ("k", "average_silhouette"))
    if sil is not None:
        st.plotly_chart(px.line(sil, x="k", y="average_silhouette", markers=True, title="R pipeline cluster-number diagnostic"), use_container_width=True)
    else:
        st.info("Silhouette diagnostics are not available.")
    st.warning("Endotype assignments and within-dataset differential characterization are exploratory, not independent validation.")
    with st.expander("Methods / Limitations"):
        st.write("The heatmap is a new descriptive aggregation: mean standardized MSG eigengenes by existing endotype. Patients are not re-clustered and no inferential statistic is estimated in this app.")
    source_box("02_wgcna_endotypes_projection/04_preliminary_endotypes_SjD.tsv", "02_wgcna_endotypes_projection/02_MSG_module_eigengenes_z.tsv")
